### ISSUE TITLE
Helm versions are now missing from what's fetched by "binenv update"

### ISSUE THREAD

**Issue by herb-kuta-lge** [devops-works/binenv#156]
https://raw.githubusercontent.com/devops-works/binenv/develop/distributions/cache.json no longer contains the versions for `helm`. They were there a few days ago.

**Comment by leucos** [comment]
Thanks for the report.
Seems that latest cache solves this. Do you confirm ?

**Comment by herb-kuta-lge** [comment]
> Seems that latest cache solves this. Do you confirm ?

Yes.

Do you understand why they were removed by https://github.com/devops-works/binenv/commit/a755fd9516a63162f89f7d0d331870ded3b795f6 ? Is this likely to happen again?

**Comment by eagafonov** [comment]
From #157: Problem with helm is fixed.

Though some other distributions have no versions:

- awless
- bat
- fzf
- github-release-notes
- gitjacker
- gosec
- havener
- helmfile
- himalaya
- k6
- kcli
- kubeconf
- micro
- peco
- phpsecscan
- procs
- sshproxy
- tf2pulumi
- ytt
