### ISSUE TITLE
Helm has no versions in cache.json

### ISSUE THREAD

**Issue by eagafonov** [devops-works/binenv#157]
https://github.com/devops-works/binenv/blob/a755fd9516a63162f89f7d0d331870ded3b795f6/distributions/cache.json#L2658

```
$ binenv version
binenv version 0.12.0 (built 2021-08-06T06:27:10Z)

$ binenv update helm
2021-09-27T14:31:40-07:00 INF retrieving distribution cache from https://raw.githubusercontent.com/devops-works/binenv/develop/distributions/cache.json
2021-09-27T14:31:40-07:00 INF fetched updates for 195 distributions

$ binenv versions helm
# Most recent first; legend: active, installed, available
helm: 
```

**Comment by leucos** [comment]
Thanks for the report.
Seems that latest cache solves this. Do you confirm ?

(dups #156)

**Comment by eagafonov** [comment]
Problem with helm is fixed.

Though some other distributions have no versions:

- awless
- bat
- fzf
- github-release-notes
- gitjacker
- gosec
- havener
- helmfile
- himalaya
- k6
- kcli
- kubeconf
- micro
- peco
- phpsecscan
- procs
- sshproxy
- tf2pulumi
- ytt

**Comment by eagafonov** [comment]
Let's move discussion to #156
Fell free to close this dup
