### ISSUE TITLE
May be group utility by usage?

### ISSUE THREAD

**Issue by patsevanton** [devops-works/binenv#175]
May be group utility by usage?

For example:

### AWS

- [awless](https://github.com/wallix/awless/): A Mighty CLI for AWS
- [aws-iam-authenticator](https://github.com/kubernetes-sigs/): A tool to use AWS IAM credentials to authenticate to a Kubernetes cluster
- [aws-vault](https://github.com/99designs/aws-): A vault for securely storing and accessing AWS credentials in development environments
- [awstaghelper](https://github.com/mpostument/awstaghelper/): AWS bulk tagging tool
- [audit2rbac](https://github.com/liggitt/audit2rbac): Autogenerate RBAC policies based on Kubernetes audit logs
- [cli53](https://github.com/barnybug/cli53/): Command line tool for Amazon Route 53
- [iamlive](https://github.com/iann0036/iamlive/): Generate an IAM policy from AWS calls using client-side monitoring (CSM) or embedded proxy
- [saml2aws](https://github.com/Versent/saml2aws/): CLI tool which enables you to login and retrieve AWS temporary credentials using a SAML IDP

### Kubernetes

- [ansible-operator](https://github.com/operator-framework/): SDK for building Kubernetes applications. Provides high level APIs, useful abstractions, and project scaffolding.
- [argocd](https://github.com/argoproj/argo-): Declarative continuous deployment for Kubernetes.
- [arkade](https://github.com/alexellis/arkade/): Declarative continuous deployment for Kubernetes.

- [helm](https://github.com/helm/helm/): The Kubernetes Package Manager
- [helm-operator](https://github.com/operator-framework/operator-sdk/): SDK for building Kubernetes applications. Provides high level APIs, useful abstractions, and project scaffolding.
- [helmfile](https://github.com/roboll/helmfile/): Deploy Kubernetes Helm Charts
- [helmwave](https://github.com/helmwave/helmwave/): 🌊 Composer for @helm Charts

- [k3d](https://github.com/rancher/k3d/): Lightweight kubernetes distribution that creates containerized k3s clusters. This means, that you can spin up a multi-node k3s cluster on a single machine using docker.
- [k6](https://github.com/loadimpact/k6/): A modern load testing tool, using Go and JavaScript - https://k6.io
- [k8stail](https://github.com/dtan4/k8stail/): tail -f experience for Kubernetes Pods
- [k9s](https://github.com/derailed/k9s/): Kubernetes CLI To Manage Your Clusters In Style!

- [kail](https://github.com/boz/kail/): kubernetes log viewer
- [kapp](https://github.com/vmware-tanzu/carvel-kapp/): A simple deployment tool focused on the concept of Kubernetes application

- [kdigger](https://github.com/quarkslab/kdigger/): kdigger is a context discovery tool for Kubernetes penetration testing.
- [ketall](https://github.com/corneliusweig/ketall/): Like `kubectl get all`, but get really all resources
- [kind](https://github.com/kubernetes-sigs/kind/): Kubernetes IN Docker - local clusters for testing Kubernetes
- [kompose](https://github.com/kubernetes/kompose/): Go from Docker Compose to Kubernetes

- [kops](https://github.com/kubernetes/kops/): Kubernetes Operations (kops) - Production Grade K8s Installation, Upgrades, and Management
- [kube-beacon](https://github.com/chen-keinan/kube-beacon/): Open Source runtime scanner for k8s cluster and perform security audit checks based on CIS Kubernetes Benchmark specification
- [kube-bench](https://github.com/aquasecurity/kube-bench/): Checks whether Kubernetes is deployed according to security best practices as defined in the CIS Kubernetes Benchmark
- [kube-dump](https://github.com/WoozyMasta/kube-dump/): Backup a Kubernetes cluster as a yaml manifest
- [kube-linter](https://github.com/stackrox/kube-linter): KubeLinter is a static analysis tool that checks Kubernetes YAML files and Helm charts to ensure  the applications represented in them adhere to best practices.
- [kubeaudit](https://github.com/Shopify/kubeaudit/): kubeaudit helps you audit your Kubernetes clusters against common security controls
- [kubecolor](https://github.com/dty1er/kubecolor/): colorizes kubectl output
- [kubeconf](https://github.com/mumoshu/kubeconf/): Switch between kubeconfigs and avoid unintentional operation on your production clusters.
- [kubectl](https://github.com/kubernetes/kubernetes/): Production-Grade Container Scheduling and Management (cli)
- [kubectl-krew](https://github.com/kubernetes-sigs/krew/): Find and install kubectl plugins
- [kubectx](https://github.com/ahmetb/kubectx/): Faster way to switch between clusters in kubectl

- [kubeeye](https://github.com/kubesphere/kubeeye/): KubeEye aims to find various problems on Kubernetes, such as application misconfiguration, unhealthy cluster components and node problems.
- [kubefwd](https://github.com/txn2/kubefwd/): Forward multiple ports in Kubernetes
- [kubens](https://github.com/ahmetb/kubectx/): Faster way to switch between namespaces in kubectl
- [kubent](https://github.com/doitintl/kube-no-trouble/): kube-no-trouble - Easily check your clusters for use of deprecated APIs
- [kubepug](https://github.com/rikatz/kubepug/): Kubernetes PreUpGrade (Checker)
- [kuberlogic](https://github.com/kuberlogic/kuberlogic/): Kuberlogic is an open-source product that deploys and manages software on top of the Kubernetes cluster and turns infrastructure into a managed PaaS.
- [kubescape](https://github.com/armosec/kubescape/): kubescape is the first tool for testing if Kubernetes is deployed securely as defined in Kubernetes Hardening Guidance by to NSA and CISA
- [kubeseal](https://github.com/bitnami-labs/sealed-secrets/): A Kubernetes controller and tool for one-way encrypted Secrets
- [kubesec](https://github.com/shyiko/kubesec/): Secure Secret management for Kubernetes (with gpg, Google Cloud KMS and AWS KMS backends)
- [kubestr](https://github.com/kastenhq/kubestr/): A tool to discover, validate and evaluate Kubernetes storage options
- [kubesurvival](https://github.com/aporia-ai/): Significantly reduce Kubernetes costs by finding the cheapest machine types that can run your workloads
- [kubeswitch](https://github.com/danielfoehrKn/kubeswitch/): The kubectx for operators
- [kubetail](https://github.com/jbvmio/kubetail/): Repository for kubetail - The pod log tailer
- [kubeval](https://github.com/instrumenta/kubeval/): Validate your Kubernetes configuration files, supports multiple Kubernetes versions
- [kustomize](https://github.com/kubernetes-sigs/): Customization of kubernetes YAML configurations
- [havener](https://github.com/homeport/havener/): Think of it as a swiss army knife for Kubernetes tasks
- [popeye](https://github.com/derailed/popeye/): A Kubernetes cluster resource sanitizer
- [peirates](https://www.inguardians.com/peirates/): Peirates - Kubernetes Penetration Testing tool
- [telepresence](https://www.telepresence.io/): Fast, local development for Kubernetes and OpenShift microservices.
- [stern](https://github.com/stern/stern/): ⎈ Multi pod and container log tailing for Kubernetes -- Friendly fork of https://github.com/wercker/stern
- [skaffold](https://skaffold.dev/): Skaffold handles the workflow for building, pushing and deploying your application, allowing you to focus on what matters most writing code.
- [sloop](https://github.com/salesforce/sloop/): Kubernetes History Visualization
- [snowcat](https://github.com/praetorian-inc/snowcat): a tool to audit the istio service mesh
- [minikube](https://github.com/kubernetes/minikube/): Run Kubernetes locally

### Terraform

- [terraform](https://www.terraform.io/): Terraform enables you to safely and predictably create, change, and improve infrastructure. It is an open source tool that codifies APIs into declarative configuration files that can be shared amongst team members, treated as code, edited, reviewed
- [terraform-docs](https://github.com/terraform-docs/terraform-docs/): Generate documentation from Terraform modules in various output formats
- [terraform-inventory](https://github.com/adammck/terraform-inventory/): terraform-inventory creates an ansible inventory from terraform
- [terragrunt](https://github.com/gruntwork-io/terragrunt/): Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
- [terrascan](https://github.com/accurics/terrascan/): Detect compliance and security violations across Infrastructure as Code to mitigate risk before provisioning cloud native infrastructure.
- [tf2pulumi](https://github.com/pulumi/tf2pulumi/): A tool to convert Terraform projects to Pulumi TypeScript programs
- [tflint](https://github.com/terraform-linters/tflint/): TFLint is a Terraform linter focused on possible errors, best practices, etc. (Terraform >= 0.12)
- [tfsec](https://github.com/tfsec/tfsec/): TFsec uses static analysis of your terraform templates to spot potential security issues.

Other

- [act](https://github.com/nektos/act/): Run your GitHub Actions locally

- [ali](https://github.com/nakabonne/ali/): Generate HTTP load and plot the results in real-time

- [annie](https://github.com/iawia002/annie/): Fast, simple and clean video downloader

- [asciigraph](https://github.com/guptarohit/asciigraph/): Go package to make lightweight ASCII line graph ╭┈╯ in command line apps with no other dependencies.

- [asciinema-edit](https://github.com/cirocosta/asciinema-): asciinema casts post-production tools

- [bat](https://github.com/sharkdp/bat/): A cat(1) clone with wings.

- [batect](https://batect.dev/): Build And Testing Environments as Code Tool

- [binenv](https://github.com/devops-works/): One binary to rule them all. Manage all those pesky binaries (kubectl, helm, terraform, ...) easily.

- [bomberman](https://github.com/c1982/bomberman/): SMTP Performance and Load Test Tool

- [bottom](https://github.com/ClementTsang/bottom/): Yet another cross-platform graphical process/system monitor.

- [broot](https://github.com/Canop/broot/): A new way to see and navigate directory trees

- [btop](https://github.com/aristocratos/btop/): A monitor of resources

- [buildx](https://github.com/docker/buildx/): Docker CLI plugin for extended build capabilities with BuildKit

- [changie](https://github.com/miniscruff/changie/): Automated changelog tool for preparing releases with lots of customization options

- [cheat](https://github.com/cheat/cheat/): cheat allows you to create and view interactive cheatsheets on the command-line.

- [check-tls-cert](https://github.com/heartbeatsjp/check-tls-cert/): Check-tls-cert is a TLS certificate checker.

- [checkip](https://github.com/jreisinger/checkip/): Check an IP address using various public services

- [chezmoi](https://github.com/twpayne/chezmoi/): Dotfile management tool

- [chisel](https://github.com/jpillora/chisel/): A fast TCP/UDP tunnel over HTTP

- [choose](https://github.com/theryangeary/choose/): A human-friendly and fast alternative to cut and (sometimes) awk

- [clog-cli](https://github.com/clog-tool/): Generate beautiful changelogs from your Git commit history

- [confused](https://github.com/visma-prodsec/): Tool to check for dependency confusion vulnerabilities in multiple package management systems

- [consul](https://releases.hashicorp.com/consul/): Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure.

- [crabz](https://github.com/sstadick/crabz): Like pigz, but rust

- [ctop](https://github.com/bcicen/ctop/): Top-like interface for container metrics

- [curlie](https://github.com/rs/curlie/): The power of curl, the ease of use of httpie.

- [datree](https://github.com/datreeio/datree/): Prevent Kubernetes misconfigurations from reaching production (again 😤 )! Datree is a CLI tool to ensure K8s manifests and Helm charts follow best practices as well as your organization’s policies.

- [delta](https://github.com/dandavison/delta/): A more intuitive version of du in rust

- [derefexo](https://github.com/deref/exo/): A process manager & log viewer for dev

- [devdash](https://github.com/Phantas0s/devdash/): Highly Configurable Terminal Dashboard for Developers and Creators

- [devspace](https://github.com/devspace-cloud/): DevSpace - The Fastest Developer Tool for Kubernetes ￼ Automate your deployment workflow with DevSpace and develop software directly inside Kubernetes.

- [dive](https://github.com/wagoodman/dive/): A tool for exploring each layer in a docker image

- [dockle](https://github.com/goodwithtech/dockle/): Container Image Linter for Security, Helping build the Best-Practice Docker Image, Easy to start

- [doctl](https://github.com/digitalocean/doctl/): The official digital ocean command line interface

- [driftctl](https://github.com/cloudskiff/driftctl/): Detect, track and alert on infrastructure drift

- [driftwood](https://github.com/trufflesecurity/driftwood): Private key usage verification

- [dstask](https://github.com/naggie/dstask/): Single binary terminal-based todo manager with git-based sync + markdown notes per task

- [dstask-import](https://github.com/naggie/dstask/): Single binary terminal-based todo manager with git-based sync + markdown notes per task (import tool)

- [duf](https://github.com/muesli/duf/): Disk Usage/Free Utility

- [dust](https://github.com/bootandy/dust/): A more intuitive version of du in rust

- [dw-query-digest](https://github.com/devops-works/): MySQL slow log analyzer. Alternative to pt-query-digest.

- [eksctl](https://github.com/weaveworks/eksctl/): eksctl is a simple CLI tool for creating clusters on AWS EKS.

- [exa](https://github.com/ogham/exa/): A modern replacement for ‘ls’.

- [exo](https://github.com/exoscale/cli/): Command-line tool for everything at Exoscale: compute, storage, dns.

- [fd](https://github.com/sharkdp/fd/): A simple, fast and user-friendly alternative to 'find'

- [fselect](https://github.com/jhspetersson/fselect/): Find files with SQL-like queries

- [fzf](https://github.com/junegunn/fzf/): fzf is a general-purpose command-line fuzzy finder.

- [gbt](https://github.com/jtyr/gbt/): Highly configurable prompt builder for Bash, ZSH and PowerShell written in Go.

- [gdu](https://github.com/dundee/gdu/): Pretty fast disk usage analyzer written in Go.

- [geesefs](https://github.com/yandex-cloud/): Finally, a good FUSE FS implementation over S3

- [gh](https://github.com/cli/cli/): GitHub’s official command line tool

- [github-release-notes](https://github.com/buchanae/github-release-notes/): Generate release notes content from GitHub Pull Request history.

- [gitjacker](https://github.com/liamg/gitjacker/): Leak git repositories from misconfigured websites

- [gitlab-terraform-manager](https://github.com/CRASH-Tech/gitlab-terraform-manager/): The tool for manage gitlab terraform backend

- [gitleaks](https://github.com/zricethezav/gitleaks/): Scan git repos (or files) for secrets using regex and entropy

- [gitui](https://github.com/extrawurst/gitui/): Blazing fast terminal client for git written in Rust

- [glab](https://github.com/profclems/glab/): An open-source GitLab command line tool

- [glow](https://github.com/charmbracelet/glow/): Render markdown on the CLI, with pizzazz! 💅🏻

- [gocloc](https://github.com/hhatto/gocloc/): A little fast cloc(Count Lines Of Code)

- [gokart](https://github.com/praetorian-inc/gokart/): A static analysis tool for securing Go code

- [golangci-lint](https://github.com/golangci/golangci-): Fast linters Runner for Go

- [goreleaser](https://github.com/goreleaser/goreleaser/): Deliver Go binaries as fast and easily as possible

- [gosec](https://github.com/securego/gosec/): Golang security checker

- [gotop](https://github.com/xxxserxxx/gotop/): Just another terminal based graphical activity monitor

- [gotty](https://github.com/yudai/gotty/): Share your terminal as a web application

- [gping](https://github.com/orf/gping/): Ping, but with a graph

- [grafana-kiosk](https://github.com/grafana/grafana-kiosk/): Kiosk utility for Grafana

- [grafana_cli](https://github.com/kckecheng/grafana_cli/): A CLI based utility to operate Grafana dashboards, folders, annotations, etc.

- [grex](https://github.com/pemistahl/grex/): A command-line tool and library for generating regular expressions from user-provided test cases

- [grizzly](https://github.com/grafana/grizzly/): A utility for managing Jsonnet dashboards against the Grafana API

- [gron](https://github.com/tomnomnom/gron/): Make JSON greppable!

- [grype](https://github.com/anchore/grype/): A vulnerability scanner for container images and filesystems

- [gws](https://github.com/StreakyCobra/gws/): Colorful KISS helper for git workspaces

- [hadolint](https://github.com/hadolint/hadolint/): Dockerfile linter, validate inline bash, written in Haskell

- [hcloud](https://github.com/hetznercloud/cli/): a tool for controlling hetzner cloud resources

- [hetty](https://hetty.xyz/): Hetty is an HTTP toolkit for security research.

- [hey](https://github.com/rakyll/hey/): HTTP load generator, ApacheBench (ab) replacement, formerly known as rakyll/boom

- [himalaya](https://github.com/soywod/himalaya/): 📫 CLI email client

- [httpx](https://github.com/projectdiscovery/httpx/): httpx is a fast and multi-purpose HTTP toolkit allow to run multiple probers using retryablehttp library, it is designed to maintain the result reliability with increased threads.

- [httpx-win](https://github.com/projectdiscovery/httpx/): httpx is a fast and multi-purpose HTTP toolkit allow to run multiple probers using retryablehttp library, it is designed to maintain the result reliability with increased threads (windows).

- [hugo](https://github.com/gohugoio/hugo/): The world’s fastest framework for building websites.

- [imgpkg](https://github.com/vmware-tanzu/carvel-imgpkg/): Allows you to store and distribute sets of files (e.g. application configuration) as images in Docker (OCI) registries

- [infracost](https://github.com/infracost/infracost/): Cloud cost estimates for Terraform

- [juicefs](https://github.com/juicedata/juicefs/): JuiceFS is a distributed POSIX file system built on top of Redis and S3.

- [kafkactl](https://github.com/deviceinsight/kafkactl/): Command Line Tool for managing Apache Kafka

- [kbld](https://github.com/vmware-tanzu/carvel-kbld/): Seamlessly incorporates image building and image pushing into your development and deployment workflows

- [kcli](https://github.com/cswank/kcli/): Kcli is a kafka read only command line browser.

- [kopia](https://github.com/kopia/kopia/): Cross-platform backup tool for Windows, macOS & Linux with fast, incremental backups, client-side end-to-end encryption, compression and data deduplication. CLI and GUI included.

- [lazygit](https://github.com/jesseduffield/lazygit/): A simple terminal UI for git commands.

- [local-php-security-checker](https://github.com/fabpot/local-php-security-checker/): PHP security vulnerabilities checker

- [logcli](https://github.com/grafana/loki/): Like Prometheus, but for logs (cli).

- [loki](https://github.com/grafana/loki/): Like Prometheus, but for logs.

- [lsd](https://github.com/Peltoche/lsd/): The next gen ls command

- [mcfly](https://github.com/cantino/mcfly/): Fly through your shell history. Great Scott!

- [micro](https://github.com/zyedidia/micro/): A modern and intuitive terminal-based text editor

- [migrate](https://github.com/golang-migrate/migrate/): CLI database migrations tool.

- [miller](https://github.com/johnkerl/miller/): Miller is like awk, sed, cut, join, and sort for name-indexed data such as CSV, TSV

- [mygopherhose](https://github.com/devops-works/mygopherhose/): Faster import for mysqldumps

- [mysql_random_data_load](https://github.com/Percona-Lab/mysql_random_data_load/): MySQL random data loader

- [naabu](https://github.com/projectdiscovery/naabu/): A fast port scanner written in go with focus on reliability and simplicity. Designed to be used in combination with other tools for attack surface discovery in bug bounties and pentests

- [naabu-win](https://github.com/projectdiscovery/naabu/): A fast port scanner written in go with focus on reliability and simplicity. Designed to be used in combination with other tools for attack surface discovery in bug bounties and pentests (windows)

- [node-problem-detector](https://github.com/kubernetes/node-problem-detector/): This is a place for various problem detectors running on the Kubernetes nodes.

- [nomad](https://www.nomadproject.io/): Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications. Nomad is easy to operate and scale and has native Consul and Vault integrations.

- [onefetch](https://github.com/o2sh/onefetch/): Git repository summary on your terminal

- [operator-sdk](https://github.com/operator-framework/operator-sdk/): SDK for building Kubernetes applications. Provides high level APIs, useful abstractions, and project scaffolding.

- [oto](https://github.com/pacedotdev/oto/): Go driven rpc code generation tool for right now (cli).

- [packer](https://www.packer.io/): Packer is a tool for creating identical machine images for multiple platforms from a single source configuration.

- [parca](https://github.com/parca-dev/parca/): Continuous profiling for analysis of CPU, memory usage over time, and down to the line number. Saving infrastructure cost, improving performance, and increasing reliability.

- [pass-checker](https://github.com/devops-works/pass-checker/): Get the entropy of your password, the maximum time needed to break it, and if the SHA1 sum appears in HaveIBeenPwned.com API.

- [peco](https://github.com/peco/peco/): Simplistic interactive filtering tool

- [pgmetrics](https://pgmetrics.io/): Collect and display information and stats from a running PostgreSQL server

- [phpsecscan](https://github.com/devops-works/): PHP vulnerability scanner (standalone or as a webserver) using FoP advisories

- [pint](https://github.com/cloudflare/pint/): Prometheus rule linter

- [pluto](https://github.com/FairwindsOps/pluto/): A cli tool to help discover deprecated apiVersions in Kubernetes

- [pomerium](https://github.com/pomerium/pomerium/): Pomerium is an identity-aware access proxy.

- [pomerium-cli](https://github.com/pomerium/pomerium/): Pomerium is an identity-aware access proxy (cli).

- [procs](https://github.com/dalance/procs/): A modern replacement for ps written in Rust.

- [promtail](https://github.com/grafana/loki/): Like Prometheus, but for logs (promtail).

- [pulumi](https://github.com/pulumi/pulumi/): Modern Infrastructure as Code. Any cloud, any language

- [pwru](https://github.com/cilium/pwru): Packet, where are you? -- Linux kernel networking debugger

- [rancher](https://rancher.com/docs/rancher/v1.6/en/): Rancher is an open source software platform that enables organizations to run and manage Docker and Kubernetes in production. (cli)

- [rg](https://github.com/BurntSushi/ripgrep/): ripgrep is a line-oriented search tool that recursively searches your current directory for a regex pattern

- [rga](https://github.com/phiresky/ripgrep-all/): ripgrep, but also search in PDFs, E-Books, Office documents, zip, tar.gz

- [scan-exporter](https://github.com/devops-works/): Scans targets and exposes results to Prometheus.

- [sd](https://github.com/chmln/sd/): Intuitive find & replace CLI (sed alternative)

- [shaloc](https://github.com/eze-kiel/shaloc/): LAN-scoped command line sharing tool with cool features (zip archives, AES-256, download limits...).

- [shdotenv](https://github.com/ko1nksm/shdotenv/): dotenv support for shell and POSIX-compliant .env syntax specification.

- [shell2http](https://github.com/msoap/shell2http/): Executing shell commands via HTTP server

- [shipyard](https://shipyard.run/): Modern cloud native development environmentss

- [slowql-digest](https://github.com/devops-works/slowql/): A package to parse slow query logs in Go, with associated tooling  (digester, replayer...), and compatible with multiple databases (MySQL, MariaDB, PerconaDB...).

- [slowql-replayer](https://github.com/devops-works/slowql/): A package to parse slow query logs in Go, with associated tooling  (digester, replayer...), and compatible with multiple databases (MySQL, MariaDB, PerconaDB...).

- [sonobuoy](https://github.com/vmware-tanzu/): Sonobuoy is a diagnostic tool that makes it easier to understand the state of a Kubernetes cluster by running a set of Kubernetes conformance tests and other plugins in an accessible and non-destructive manner.

- [sops](https://github.com/mozilla/sops/): Simple and flexible tool for managing secrets

- [sshproxy](https://github.com/cea-hpc/sshproxy/): Proxy SSH connections on a gateway

- [ssllabs-scan](https://github.com/ssllabs/ssllabs-scan/): A command-line reference-implementation client for SSL Labs APIs, designed for automated and/or bulk testing.

- [starship](https://github.com/starship/starship/): The minimal, blazing-fast, and infinitely customizable prompt for any shell!

- [subfinder](https://github.com/projectdiscovery/subfinder/): Subfinder is a subdomain discovery tool that discovers valid subdomains for websites. Designed as a passive framework to be useful for bug bounties and safe for penetration testing.

- [subfinder-win](https://github.com/projectdiscovery/subfinder/): Subfinder is a subdomain discovery tool that discovers valid subdomains for websites. Designed as a passive framework to be useful for bug bounties and safe for penetration testing (windows).

- [swag](https://github.com/swaggo/swag/): Automatically generate RESTful API documentation with Swagger 2.0 for Go.

- [swagger](https://github.com/go-swagger/go-swagger/): Swagger 2.0 implementation for go

- [sysz](https://github.com/joehillen/sysz/): An fzf terminal UI for systemctl

- [tanka](https://github.com/grafana/tanka/): Flexible, reusable and concise configuration for Kubernetes

- [task](https://github.com/go-task/task/): A task runner / simpler Make alternative written in Go

- [taskctl](https://github.com/taskctl/taskctl/): simple modern alternative to GNU Make.

- [teler](https://github.com/kitabisa/teler/): Real-time HTTP Intrusion Detection

- [termshark](https://github.com/gcla/termshark/): A terminal UI for tshark, inspired by Wireshark

- [toji](https://github.com/leucos/toji/): Toji is a Toggle ➡ Jira bridge: sync your Toggl entries directly into Jira issues worklog

- [traefik](https://github.com/traefik/traefik/): The Cloud Native Application Proxy

- [trivy](https://github.com/aquasecurity/trivy/): A Simple and Comprehensive Vulnerability Scanner for Containers, Suitable for CI

- [upx](https://github.com/upx/upx/): UPX - the Ultimate Packer for eXecutables

- [vagrant](https://www.vagrantup.com/): A toolfor building and distributing development environments.

- [vault](https://www.vaultproject.io/): A tool for secrets management, encryption as a service, and privileged access management

- [vmctl](https://github.com/VictoriaMetrics/vmctl/): Victoria Metrics command line tool

- [websocat](https://github.com/vi/websocat/): About Command-line client for WebSockets, like netcat (or curl) for ws:// with advanced socat-like functions

- [xh](https://github.com/ducaale/xh/): Friendly and fast tool for sending HTTP requests

- [yh](https://github.com/andreazorzetto/yh/): YAML syntax highlighter to bring colours to kubectl output

- [yj](https://github.com/sclevine/yj/): Convert between YAML, TOML, JSON, and HCL.

- [yor](https://github.com/bridgecrewio/yor/): Extensible auto-tagger for your IaC files. The ultimate way to link entities in the cloud back to the codified resource which created it.

- [yq](https://github.com/mikefarah/yq/): a lightweight and portable command-line YAML processor

- [ytt](https://github.com/vmware-tanzu/carvel-ytt/): YAML templating tool that works on YAML structure instead of text

**Comment by patsevanton** [comment]
If idea is ok, i can later rewrite list.

**Comment by leucos** [comment]
Interesting. I would rather use tags which are more versatile.
I guess we should not rush this and check how to implement it in binvenv before tagging the whole list

**Comment by patsevanton** [comment]
Ok
