### ISSUE TITLE
Add search command

### ISSUE THREAD

**Issue by eze-kiel** [devops-works/binenv#19]
This would allow to search if a binary is available in binenv without having to use `versions` and then search through the output to find it.

**Comment by leucos** [comment]
Interesting. Any "pseudo-output" so we can see how this could look ?

**Comment by eze-kiel** [comment]
I was thinking about something that emulate a `grep` :
```
$ binenv versions | grep krew
krew: 0.4.0 0.3.4 0.3.3 0.3.2 0.3.1 0.3.0 0.2.1 0.2.0 0.1.1 0.1.0-alpha.1
```
Having the versions available displayed can be nice
