### ISSUE TITLE
Cache update Github Workflow is not working anymore

### ISSUE THREAD

**Issue by angrox** [devops-works/binenv#190]
The cache update process seems not to run anymore: 
Looking at https://github.com/devops-works/binenv/actions/workflows/update_cache.yml the last update was 5 month ago.

**Comment by leucos** [comment]
sorry I just see your issue now.

yes, this is on purpose; it was totally broken and not reliable. I do not have a replacement for now, except from running it from time to time and push.

**Comment by angrox** [comment]
I can't see the error logs from the workflow anymore - what was the probelm?

**Comment by leucos** [comment]
I do not remember exactly, but afaik it was breaking the cache sometimes.
And may be was rate limited too.

If the cache is not fresh enough, you can run `binenv update -f` and it should update all available distributions versions.

Note however that you'll need a GH token for this or you will hit the rate limit.

**Comment by angrox** [comment]
Thanks for the answers! Closing issue

**Comment by leucos** [comment]
Will try to reenable it after I merge #191 and fix #171
