### ISSUE TITLE
ctop 0.7.7 installation fails

### ISSUE THREAD

**Issue by riccardopedrielli** [devops-works/binenv#196]
The installation of https://github.com/bcicen/ctop fails for version `0.7.7`.

That is because they changed the release name format, adding the `v`.

`Old: https://github.com/bcicen/ctop/releases/download/0.7.6/ctop-0.7.6-linux-amd64`
`New: https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64`

**Comment by leucos** [comment]
thanks a lot for spotting this @riccardopedrielli 
this is fixed (`binenv update` and you should be okay).
