### ISSUE TITLE
procs 0.12.2 installation fails

### ISSUE THREAD

**Issue by riccardopedrielli** [devops-works/binenv#197]
The installation of https://github.com/dalance/procs fails for version `0.12.2`.

That is because they changed the name format of the zip archive.
The os part is now `linux` instead on `lnx`.

`Old: https://github.com/dalance/procs/releases/download/v0.12.1/procs-v0.12.1-x86_64-lnx.zip`
`New: https://github.com/dalance/procs/releases/download/v0.12.2/procs-v0.12.2-x86_64-linux.zip`

**Comment by leucos** [comment]
thanks a lot for spotting this @riccardopedrielli 
this is fixed (`binenv update` and you should be okay).
