### ISSUE TITLE
kubeeye 0.5.0 installation fails

### ISSUE THREAD

**Issue by riccardopedrielli** [devops-works/binenv#208]
The installation of https://github.com/kubesphere/kubeeye fails for version 0.5.0.

That is because they changed the package name format, adding the `v`.

`Old: https://github.com/kubesphere/kubeeye/releases/download/v0.5.0/kubeeye-0.5.0-linux-amd64.tar.gz`
`New: https://github.com/kubesphere/kubeeye/releases/download/v0.5.0/kubeeye-v0.5.0-linux-amd64.tar.gz`

**Comment by leucos** [comment]
Also, to make the matter more entertaining, the binary has been renamed to "ke" :)
