### ISSUE TITLE
k9s changed arch from x86_64 to amd64 in binary archives

### ISSUE THREAD

**Issue by EnochTheWise** [devops-works/binenv#228]
`2023-02-08T15:34:37+07:00 ERR unable to install "k9s" (0.27.2) error="unable to download binary at https://github.com/derailed/k9s/releases/download/v0.27.2/k9s_Linux_x86_64.tar.gz: 404 Not Found"`

**Comment by leucos** [comment]
this is a dup of https://github.com/devops-works/binenv/issues/226
please reopen the previous issue if you're still experiencing problems.

it also helps providing a little context instead of just dumping an error.

for instance, did you `binenv update` ?
