### ISSUE TITLE
Unable to read distributions error="unable to fetch distributions: Get \"https://raw.githubusercontent.com/devops-works/binenv/master/distributions/distributions.yaml\": proxyconnect

### ISSUE THREAD

**Issue by kenni-shin** [devops-works/binenv#246]
Is there any way don't check or skip distributions.yaml file if have offline system without internet access?

**Comment by leucos** [comment]
Can you tell me what command you are executing ?

**Comment by kenni-shin** [comment]
Im trying use downloaded binaries in  .binenv in docker without .cache/binenv and .config/binenv. Just thinking is there any way to skip fetchDistributions like with env variable or something.

**Comment by kenni-shin** [comment]
Very strange ill getting this on binary launch and ill coped only .binenv folder.
```logs
2024-02-07T21:26:38Z INF updating distribution list
2024-02-07T21:27:08Z ERR unable to read distributions error="unable to fetch distributions: Get \"[https://raw.githubusercontent.com/devops-works/binenv/master/distributions/distributions.yaml\](https://raw.githubusercontent.com/devops-works/binenv/master/distributions/distributions.yaml/)": proxyconnect tcp: dial tcp 192.168.1.1:8888: i/o timeout"
Error: Process completed with exit code 1.
```

**Comment by leucos** [comment]
can you paste the command you are running please ?

**Comment by kenni-shin** [comment]
I tried to make docker image with preinstalled binaries with command `binenv install -l`, but coped only  /root/.binenv dir.
So when have tried to execute binary directly like `/root/.binenv/sops` and got this error.
Solving this problem coping /.config/binenv and .cache/binenv.
We can close this issue ill think.
