### ISSUE TITLE
binenv install bat on linux: got manpage instead of binary

### ISSUE THREAD

**Issue by axgkl** [devops-works/binenv#259]
```
admin@bast:~$ uname -a
Linux bast 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
admin@bast:~$ binenv install bat
2024-07-25T08:00:46Z WRN version for "bat" not specified; using "0.24.0"
fetching bat version 0.24.0 100% |█████████████████████████████████████████████| (2.9/2.9 MB, 191.745 MB/s)
2024-07-25T08:00:47Z INF "bat" (0.24.0) installed
admin@bast:~$ bat
2024-07-25T08:00:50Z FTL unable to execute bat error="exec format error"

admin@bast:~/.binenv/binaries/bat$ head 0.24.0
.TH BAT "1"
.SH NAME
bat \- a cat(1) clone with syntax highlighting and Git integration.
.SH "USAGE"
.IP "bat [OPTIONS] [FILE]..."
.IP "bat cache [CACHE-OPTIONS] [--build|--clear]
.SH DESCRIPTION
bat prints the syntax-highlighted content of a collection of FILEs to the
terminal. If no FILE is specified, or when FILE is '-', it reads from standard input.
```

> There are no tests. I will probably go to hell for this.

:shushing_face: 

why not pumping at least the newest versions through a build test to see if sth is broken and take it out if so?

**Comment by leucos** [comment]
Such test exists; it is very slow as you can imagine and it doesn check if the downloaded stuff is a binary (eay to change).

Thanks for the report, will take a look at it

**Comment by leucos** [comment]
Could you try to  `binenv uninstall bat && binenv install bat` please ?

**Comment by axgkl** [comment]
![2024-07-26_1016x458_scrot](https://github.com/user-attachments/assets/f8db5b52-e841-4d91-862b-a0f2da256a98)

Merci bien.

And sry, just saw your statement in the README, did not look into the Makefile -> should be easy to add the filetype test :hand_with_index_finger_and_thumb_crossed:
