### ISSUE TITLE
Suggestions for more binaries :)

### ISSUE THREAD

**Issue by deknos** [devops-works/binenv#43]
Hi, i have a couple of suggestions of binaries i use in several projects:

- ~~fzf https://github.com/junegunn/fzf a great commandline tool~~
- pyenv https://github.com/pyenv/pyenv with that you can manage multiple python installations
- lens https://github.com/lensapp/lens graphical kubernetes client
- github-cli https://github.com/cli/cli  .. :D
- signify https://github.com/aperezdc/signify tool for signing binaries
- https://github.com/artipie/artipie/ artefact manager which i use
- minio https://github.com/minio/minio s3 storage "emulator"
- yq https://github.com/mikefarah/yq like jq but with yaml

i am not sure if you can do this stuff too, but perhaps they will do releases one day:

- hashpipe https://github.com/jbenet/hashpipe verifies signatures
- gron https://github.com/tomnomnom/gron really great if you wanna grep json
- distrib-dl (https://github.com/nodiscc/distrib-dl or https://gitlab.com/nodiscc/distrib-dl, last one seems to be newer) with this you can download distribution iso images verified.
- polynimbus https://github.com/polynimbus/polynimbus another cloud deployment tool

and another idea, did you think about installing other package managers? like

- nix pkg manager
- homebrew for /linuxbrew for linux 
- python pip ? https://pip.pypa.io/en/stable/installing/

the second and third blocks are just suggestions. i am glad either way, i will DEFINITELY use your tool. Thanks for this!

**Comment by deknos** [comment]
- upt https://github.com/sigoden/upt would be very good as well, a colleague uses that for testing. and we should ask upt if you are included

**Comment by deknos** [comment]
- https://github.com/Azure/azure-cli :D

**Comment by deknos** [comment]
the more about i think about our projects in our company, the more projects there are:

- https://github.com/conan-io/conan

**Comment by Sispheor** [comment]
I would add openshif client (oc).

**Comment by leucos** [comment]
Thanks for the suggestions @Sispheor @deknos :+1:  ! 

If you feel like so, you can get a shot at it adding those to [distributions/distributions.yaml](https://github.com/devops-works/binenv/blob/develop/distributions/distributions.yaml) (branch-off develop).

If you don't, no worries, we'll take care of this.

**Comment by deknos** [comment]
i will give it a try! thanks!

**Comment by deknos** [comment]
fzf is almost done, if you can merge it. i will also look at the other ones. but i think i have to look into your code.
and the rate limit is really a little bothering. for example, i cannot use other git repositories other than yours, or branches from yours or others as base config for the distributions. which is a lockin. but that's for another time. your project is really cool, sorry that i do not have the time to work faster.

**Comment by deknos** [comment]
i am working on yq. i just found another old project i am using:
* https://github.com/adammck/terraform-inventory i will look into it.

**Comment by emmetog** [comment]
Here are a handful more:
* https://github.com/yarnpkg/yarn
* https://github.com/composer/composer
* https://docs.ansible.com/ansible/devel/installation_guide/intro_installation.html

**Comment by leucos** [comment]
> Here are a handful more:
> 
> * https://github.com/yarnpkg/yarn
> * https://github.com/composer/composer
> * https://docs.ansible.com/ansible/devel/installation_guide/intro_installation.html

Thanks for the suggestions @emmetog 

However we can only install binaries (that stands on their own). I am afraid none of the above can do that. Ansible definitively requires a lot of supporting libraries (we use virtualenv for this, and have a dedicated virtualenv per Ansible version).

May be composer can fit, but I am wondering what is the added value of using binenv here ? Same for yarn. I am afraid there require some proper environment settings (node version, PHP version, php.ini setup, etc...). So I am afraid that trying to manage versions of those things outside their ecosystem is prone to failure.

The goal is really to handle self-sustaining binaries. We will never do what projects like rubyenv/phpenv/goenv can do.

**Comment by leucos** [comment]
> fzf is almost done, if you can merge it. i will also look at the other ones. but i think i have to look into your code.
> and the rate limit is really a little bothering. for example,

Well, the rate limit is not from us. Github rate limits connections for non authenticated users.
See https://github.com/devops-works/binenv#updating-versions-using-a-token

> i cannot use other git repositories other than yours, or branches from yours or others as base config for the distributions. which is a lockin. 

I do not really understand what you mean here.
Please open a separate issue if possible so we do not turn this issue in some kind of catch-all.

**Comment by leucos** [comment]
@deknos some info about your wishlist;

- pyenv: won't work; this is not a single binary
- lens: won't work (appimage, not a binary)
- github-cli: already there (see `gh`)
- signify: no binary releases
- https://github.com/artipie/artipie/ : no binary release
- minio: just checked how they handle release, we will have a hard time on this one :/

**Comment by deknos** [comment]
yeah, i thought minio and artipie will be single binaries, but those are both not single binaries :/

**Comment by deknos** [comment]
i mean, if it's for me, you can close the issue. i will follow up on the possible projects and ask them for releases (for exampel with signify)
or you can post a whislist on your documentation, where stuff like that is listed an people can post pull request. the ones which are possible and interesting for me, i will post PRs :)
