### ISSUE TITLE
problems within a fresh machine

### ISSUE THREAD

**Issue by deknos** [devops-works/binenv#46]
Hi,
due to some problems i followed your steps again in a vagrant box and after downloading and chmoding the binary i got that error request:
`vagrant@debian10:~$ ./binenv update
updating distributions  76% |.....                          | (57/75, 4 it/s) [16s:5s]2020-11-23T15:21:15Z ERR unable to fetch versions for "stern" error="github rate limit is close: remaining 4 of 60; please retry after 2020-11-23 16:20:59 +0000 UTC"`

it looks like i get an error with the distributions. i am not sure, why this happens. i have not much requests to github atm.
could it be that fetching your LATEST binenv creates some problem? should you at least use a binenv from a release where all the distributions are verified? or is it another problem?

**Comment by Cleming** [comment]
Hi,
I think it's the same issue #45

**Comment by deknos** [comment]
yep, that's it. thanks
