### ISSUE TITLE
`--develop` flag for distributions

### ISSUE THREAD

**Issue by leucos** [devops-works/binenv#5]
This would allow fetching `distributions.yaml` from the develop branch

**Comment by leucos** [comment]
may be merge `defintions` with update ?

`binenv update --definitions` + `binenv update --definitions --develop`

**Comment by deknos** [comment]
in #50 i made a suggestion as well. with --raw or without :)

**Comment by leucos** [comment]
I guess this would make the API a bit too complicated for a very small edge case.We'd rather close this until we're sure that cahce + distributions will stay in this repo.
