### ISSUE TITLE
Please add https://github.com/ogham/dog Command-line DNS client

### ISSUE THREAD

**Issue by patsevanton** [devops-works/binenv#51]
Please add https://github.com/ogham/dog Command-line DNS client

**Comment by leucos** [comment]
Hello @patsevanton 
Thanks for the suggestion.
We tried that already. Unfortunately, it seems that `dog` really requires compiling.

Here is what I get when I download the binary and run it:

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by dog)
```
