### ISSUE TITLE
Install instructions broken - Error: unknown flag: --cache

### ISSUE THREAD

**Issue by cablespaghetti** [devops-works/binenv#68]
Trying to follow the README to install binenv on Linux I get this error:

```
./binenv update --cache
Error: unknown flag: --cache
```

Removing the cache flag seems to work though.

Thanks!

**Comment by deknos** [comment]
did you try binenv update binenv?

**Comment by leucos** [comment]
Yes the `--cache` options has been removed and I overlooked this in the documentation. Thanks for reporting !
