### ISSUE TITLE
OS/Arch Exclusions

### ISSUE THREAD

**Issue by leucos** [devops-works/binenv#9]
Implement OS/architecture exclusions

**Comment by jakubvokoun** [comment]
@leucos Wouldn't it be easier to (optionaly) list supported OS - Arch pairs?

**Comment by leucos** [comment]
Yes indeed !

**Comment by jakubvokoun** [comment]
OK then, PR will come soon. :-)

**Comment by leucos** [comment]
Awesome ! 
If we could keep the keys lowercase that would be great.

Good luck !

**Comment by jakubvokoun** [comment]
> Awesome !
> If we could keep the keys lowercase that would be great.
> 
> Good luck !

No problem

**Comment by leucos** [comment]
@jakubvokoun I released a new version containing your contribution (and gokart is taking advantage of this)

You can `binenv update -f binenv && binenv install binenv` to play with it if you wish.
